### ISSUE TITLE
initial release outline

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/guardian#1]
events:

- [x] user logs in `++score?`
- [x] user registers
- [x] user posts
- [x] user discussion approved `++score`
- [x] post of user deleted `--score`
- [x] discussion of user deleted without replies `--score`
- [x] user suspended `--score`
- [ ] screen content of posts  `score`
  - [ ] number of links
- [x] user changes mail address

metrics:

- [x] client ip
- [x] client hostname
- [ ] client header information:
  - [x] browser
  - [x] os
  - [x] locale/language
  - [ ] timezone
- [x] email address
- [x] locale configured
- [ ] avatar comparison
  - https://github.com/lupka/phpunit-compare-images requires imagick
  - https://github.com/vajiralasantha/PHP-Image-Compare requires gd
- [x] time since last event (by looking at created_at of last event)
- [ ] Levenshtein distance to other usernames or mail addresses
- [ ] user has taken a look (browsed around) before posting
- [ ] how fast a user posts a reply inside an existing discussion based on the number of posts
- [ ] post title
  - [ ] contains or is url
  - [ ] equals other discussions completely

actions:

- [ ] ban and prune, which suspends a user permanently and deletes all discussions of this user without replies, others are soft deleted, also soft deletes all posts
- [ ] compare two users side by side
- [ ] suspend/block ip's, hostnames, mail domains using regexes
- [ ] redirect suspended users to a specific url (eg tag, custom page or outside url)
- [ ] configure floodgate based on total `score`
- [ ] block access by bots from specific routes/tags
- [x] block access by bots from logging in and registering
- [x] allow specific groups to act without creating footprints

considerations:

- [ ] move heavy work to flagrow/console scheduled tasks
- [ ] synchronise banlist/users/metrics to flagrow.io to re-use on other installations

documentation:

- [ ] privacy 😈 

---
Related:

- https://github.com/gravure/flagrow/issues/8

**Comment by luceos** [comment]
Let's allow metrics to be configurable and extensible. If we look at how fail2ban is set up we could also modularise this.

The Footprint class hoards all information. What information is gathered depends on enabled Metric classes, these have to implement a Metric interface/contract.

We should also have a remote (flagrow.io) database that stores common spam markers. Eg discuss recently has been targeted by spam related to urls with the regex `fanatic(.*)shop.com` we should be able to sync this information and use it to our advantage.

**Comment by KyrneDev** [comment]
Let's also integrate StopForumSpam as a metric

**Comment by Ralkage** [comment]
Closing this issue as this extension is now depreciated.
